### PR TITLE
minimize keyboard on animate and clear idb

### PR DESCRIPTION
**Pull request by cup-noodlehS**
not tested lol

### CODE REVIEW

**Comment by cup-noodlehS** [comment]
@maxellmilay review aydul

**Comment by maxellmilay** [comment]
> not tested lol

@cup-noodlehS test this please HAHAHA

**Comment by cup-noodlehS** [comment]
guds na @maxellmilay

**Comment by cup-noodlehS** [comment]
Merge plez @maxellmilay arun maayu ako safari uwu

**Review by maxellmilay — APPROVED** [review]
@cup-noodlehS LGTM :fire:

**Pull request merged**
